server:
  port: 2000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/product_db
    username: root
    password: root123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  # Setting live reload for Thymeleaf template
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: file:src/main/resources/templates/
  messages:
    basename: i18n/messages
  web:
    locale-resolver: fixed
    locale: vi_VN
    # Setting live reload for Thymeleaf template
    resources:
      static-locations: file:src/main/resources/static/
      cache:
        period: 0